### ISSUE TITLE
Launch the Java console

### ISSUE THREAD

**Issue by pauleveritt** [Macuyiko/minecraft-python#11]
There isn't a good way to launch the Java console. The screencast shows a log message about launching the GUI, but the string "GUI" no longer appears in the repo. It looks like that was, at some point, removed.

For the 0.0.1 milestone (which is basically the "wrap a bow around what is currently there"), we should get the Java console working again. @Macuyiko can you confirm that it no longer works in a fresh checkout for you?

**Comment by Macuyiko** [comment]
Correct, the GUI console was removed in favor of logging in through a telnet client, the web based interface, or the GUI client, in https://github.com/Macuyiko/Jycraft/tree/master/ServerEditorJava

Before, the Canary plugin indeed spawned a GUI console (which was actually based on Python code invoked through Jython, not Java code). The reason why this was removed is: 1) the GUI would pop-up on the server where the Minecraft server was running. Not very helpful when the server and client or not running on the same machine. 2) based on how the GUI code was structured, it was impossible to separate it out in a separate thread or do thread management (Spigot for instance requires that some commands are ran in a special thread so as to not to overload the main thread, you'll find evidences of this in the current code as well).

If we want, we can still foresee a simple GUI console (written in native Java, then) which is spawned as soon as the plugin is started. Is this absolutely necessary though? I think it makes more sense to keep the client-server architecture and code base decoupled.

**Comment by pauleveritt** [comment]
I don’t mind at all getting rid of the Java client. I agree that spawning it on what might be a remote server is a bad idea.

I agree that it should change to using the websocket client/server model, _if_ we want to keep it. We, meaning you. :) Java’s not my thing.

It’s featured on the home page, though, so perhaps we should remove it from the docs until we bring it back to life.

—Paul

**Comment by pauleveritt** [comment]
This ticket can be closed. We have another ticket about cleaning it up, but this answers the question for the 0.0.1 release.
