### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by pitust** [Macuyiko/minecraft-python#19]
Can anyone use /py command? If so, it seems not a good idea to use this plugin because anyone can hack my server.

**Comment by Macuyiko** [comment]
By default, yes, though this can be disabled in the config, and server ports put behind an authentication mechanism.

There isn't much support out of the box for authentication, might think about adding this later.

**Comment by Macuyiko** [comment]
The new release contains permissions for the chat commands (set to ops by default). The Telnet / Websocket interface is left as is (as these can be disabled / proxied, which for now is my preferred way to go about this).
