### ISSUE TITLE
Connect with Vault

### ISSUE THREAD

**Issue by otlet** [Macuyiko/minecraft-python#20]
Hi!

I try to connect Python plugin and [Vault by Milkbowl](http://milkbowl.github.io/VaultAPI/) but had a problem.

```python
from mcapi import *

from net.milkbowl.vault import economy

@asynchronous()
def cmd_make_deposit(caller, params):
    name = caller.getName()
    print economy
    params_length = len(params)
    print params_length


add_command('deposit', cmd_make_deposit)
```

But i still got:

```python
[20:42:28 WARN]: Traceback (most recent call last):
  File "/home/otlet/mc_server/./python-plugins/money_deposit.py", line 4, in <module>
    import net.milkbowl.vault
ImportError: No module named milkbowl
```

With `org.Bukkit.xxx` this work, but with Vault, EssentialsX and others plugins i try - this didn't work.

I know that I'm doing something wrong, I have been combining so much time that unfortunately I have to ask how to import Vault or other plugins?

**Comment by Macuyiko** [comment]
By default, this plugin does not add other plugin JARs to the Jython class path. A workaround would be to add the JAR file for Vault to the "lib-common" directory, after which imports should work.

**Comment by otlet** [comment]
This workaround doesn't work, because after server restart, package was remove.
lib-common was regenerated after server restart.

**Comment by Macuyiko** [comment]
Please try the release v2019-03-31

This allows creating a folder called `lib-custom` in which you can drop your JAR files that you want to include in the Python interpreter.
