### ISSUE TITLE
Documentation & Examples

### ISSUE THREAD

**Issue by konsumer** [Macuyiko/minecraft-python#35]
I can't seem to get `BlockDamageEvent` to work. I did this in a file in python-plugins/:

```python
from mcapi import *
from org.bukkit.event.block import BlockDamageEvent

@asynchronous()
def block_damage_event(e):
  yell('boom!')

add_event_listener(BlockDamageEvent, block_damage_event)
```

It fires other things in same file (like `PlayerJoinEvent`) but not this.

Is there a python-oriented set of docs anywhere?

**Comment by konsumer** [comment]
Actually, this worked great, as a plugin in python-plugins:

```python
from mcapi import *
from org.bukkit.event.block import BlockBreakEvent

# when a player breaks a block, spawn a chicken
@asynchronous()
def block_break_event(e):
  player = e.getPlayer()
  yell('you break a block, you get a chicken %s!' % player.getName())
  chicken = spawn(lookingat(player))

add_event_listener(BlockBreakEvent, block_break_event)
```
I suppose this issue can be closed, but I'd still like to get some sort of reference, if it's available, as it took me a while to figure out to use `BlockBreakEvent` instead of `BlockDamageEvent`.

**Comment by Macuyiko** [comment]
Actually BlockDamageEvent works as well when testing it.

![image](https://user-images.githubusercontent.com/271897/87793468-9b2df380-c845-11ea-8b0c-aa416d577cfc.png)

According to the Bukkit API docs:

- https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/block/BlockDamageEvent.html
- https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/block/BlockBreakEvent.html

BlockBreakEvent is called when a block is broken by a player. BlockDamageEvent when a block receives damage from a player.

**Comment by konsumer** [comment]
Ah! So maybe the key issue was loading a script, instead of putting it in a plugin in `python-plugins`. This wasn't at all clear to me, and it seemed like it should work the same, but it only seems to work loaded as a global plugin.

Maybe more examples would be a helpful way to show the correlation to the java docs? Are there any examples you would like to see, that I could make? Maybe I could document the whole process (even including getting the server setup) so it's clear how it all fits together?

**Comment by Macuyiko** [comment]
Well, I tried it both as a script and as a plugin in `python-plugins`, both cases worked for me, so it's a bit strange of an issue.

> Maybe more examples would be a helpful way to show the correlation to the java docs? Are there any examples you would like to see, that I could make?

The more examples the merrier, and I'm open to accept pull requests. The correlation to the Java docs is more or less a one-to-one mapping, except for the cases where it isn't and a bit of boilerplate Python functions are necessary due to Jython's difficulty in allowing to implement Java interfaces, i.e. that's what the `add_event_listener` function helps with. Nevertheless, this still assumes that one is pretty well versed in the Bukkit API, so also here some examples would be welcome.

**Comment by konsumer** [comment]
I am working through some tutorial ideas [here](https://github.com/konsumer/minecraft-python-example). After I'm done, do you want me to PR for a subdir like tutorial?

**Comment by konsumer** [comment]
I worked out what I already know how to do, and included explanations. I still have a few tutorials I want to work on, but that should get people started. I recommended `/pyrestart` for reloading the python scripts, because it seems like that's what it's for, but it doesn't seem to actually reload the plugins. I also tried `/reload confirm` (on paper server) and it causes an error about the websocket port already being in-use. Is there a better way to reload python plugins? Maybe some sort of module auto-reload would be cool, for quickly playing around with plugins.

**Comment by konsumer** [comment]
I also made a [web-based python REPL](https://mcpyrepl.surge.sh/) so users don't need to install a local copy of python3. It's pretty rudimentary now, but I can add more features as I work them out (backspace, arrow-history-line navigation, maybe even auto-completion.)

![Screenshot from 2020-07-17 19-30-35](https://user-images.githubusercontent.com/83857/87842807-3e8e0100-c864-11ea-8fd6-b628ea512e22.png)

**Comment by Macuyiko** [comment]
Very nice work! This project also included a web based interface in the past but was removed as I felt that would be better left to a separate repository/project and keep this one relatively focused.

> I recommended /pyrestart for reloading the python scripts, because it seems like that's what it's for, but it doesn't seem to actually reload the plugins. I also tried /reload confirm (on paper server) and it causes an error about the websocket port already being in-use

Those are some good points, `pyrestart` restarts the player-allocated interpreter, not the plugin interpreter. That should go in its own command. `/reload confirm` not being able to rebind to the websocket port is most likely a bug. I will look into modifying the plugin so it closes its ports down when unloading.

**Comment by konsumer** [comment]
> This project also included a web based interface in the past but was removed as I felt that would be better left to a separate repository/project and keep this one relatively focused.

That makes sense. Mine is pretty rudimentary, so I should take a look at yours and see if I can improve it. I am happy to structure these 3 projects (repl, examples, minecraft-python itself) however you like. If they reference each other, I think it would make it much easier to get started with minecraft-python, but they totally don't need to be in the same repo at all.


> `pyrestart` restarts the player-allocated interpreter, not the plugin interpreter. That should go in its own command. 

Makes sense. it might be confusing to also have a `pyreload` command or something. Maybe an arg, like `/pyrestart plugins`?

> I will look into modifying the plugin so it closes its ports down when unloading.

Sounds good. I can do any testing you need (I am primarily on amd64 linux, and have some vmachines for testing windows & osx) or even help with code (I am a bit rusty, but decent with java.)

Am I going about it wrong, by working with plugins? should I be trying to do tutorials in `pyload`ed files or some other way?

With web-stuff I use hot-reloading to get immediate feedback, like swapping out react components without changing the state or args (props), and it really helps see the effects of changes quickly, and it's a big help with experienced programmers and newbs, alike. To a lesser degree, just auto-reloading is also useful: like swapping out the whole page (or in this case the entire python-runtime instance) when something changes. I dunno how feasible or useful for other people these are, with java/python but it would be cool, if it's not too hard to setup.

I am imagining that minecraft-python will be helpful for a young friend I am helping to teach programming to. He already knows a bit of python (played with pygame, etc) and likes minecraft, and rather than toss him into the whole java ecosystem & language, compiling and injecting plugin-code, etc, this seems like a much nicer & more familiar starting-point.
