### ISSUE TITLE
"A" Character in Front of SendMessage

### ISSUE THREAD

**Issue by AbnormalMatrix** [Macuyiko/minecraft-python#39]
Hello,
When using this I am running the following code to send a message to a player in red text:
`player.getPlayer().sendMessage(str(ChatColor.RED) + str("You are on the red team"))`
However, when I run that line, I get
![Screen Shot 2020-10-04 at 11 06 49 AM](https://user-images.githubusercontent.com/36489685/95022044-eb8d4400-0631-11eb-9d95-7ce9c1352163.png)
instead. Why is there that weird "A" character and how can I get rid of it?
Thanks!

**Comment by Macuyiko** [comment]
Jython 2 follows Python's 2 str behavior, so str is ASCII. To work around this, either use `unicode` (which is equivalent to `str` in Python 3) or `toString()`:

    player().sendMessage(unicode(ChatColor.RED) + "test")
    player().sendMessage(ChatColor.RED.toString() + "test")
