### ISSUE TITLE
Can we get a shutdown event?

### ISSUE THREAD

**Issue by Tendrid** [Macuyiko/minecraft-python#42]
I've noticed theres no bukkit event for a shutdown, and it doesnt look like this code supports it either.  I need a way to gracefully save in-memory data when a server is shutting down or when the plugins are restarting, is there any way i can make that happen with the current code?

**Comment by Macuyiko** [comment]
That would probably require some sort of custom hook in onDisable() of the plugin itself.

**Comment by Tendrid** [comment]
Ya before i left the comment I tried creating a python class with onDisable, and registering that as a plugin, but it didnt seem to work.  I didnt keep going, because i wasnt sure if it was even possible.  If you have any hints, i'm happy to go back and keep trying.

(i also tried using class destruction in python, but it was never called)

**Comment by Macuyiko** [comment]
The latest release (v2021-06-10) now provides a method which should work, by allowing to register functions to be called when onDisable fires on the Java side. Let me know whether that works.
