### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by oddmario** [Macuyiko/minecraft-python#45]
Hello,

I've seen this project and I liked the idea.

I was wondering if this is still actively developed, and does it work for 1.16.5?

Kind regards.

**Comment by omgamer** [comment]
Yea maybe

**Comment by abbas-rz** [comment]
1.9 pvp sucks is it backwards compatible with 1.8 ??
thanks!

**Comment by Macuyiko** [comment]
Still alive. Release of today works for 1.16.5. Backwards compatible but you might add to recompile the JAR yourself using a matching Spigot JAR.

**Comment by oddmario** [comment]
> Still alive. Release of today works for 1.16.5. Backwards compatible but you might add to recompile the JAR yourself using a matching Spigot JAR.

Thank you so much! :)

It's 1.17 soon

**Comment by Macuyiko** [comment]
1.17 release now available.
