### ISSUE TITLE
Importing the Keyboard Python module

### ISSUE THREAD

**Issue by rsiebertdev** [Macuyiko/minecraft-python#48]
Some built-in modules like `time` works within minecraft-python, but I can't figure out how to install the Keyboard module so I can import it?

**Comment by oddmario** [comment]
See #47

**Comment by Macuyiko** [comment]
Indeed - though note that the module will hook keyboard events server-side, e.g. on the Spigot server, not on the clients' side. That's probably not what you want. Implementing client side hooks is not possible (it would be a huge security issue if it would be).
