### ISSUE TITLE
How can i use Python3.7 or How can i use python libraries example Flask with Minecraft

### ISSUE THREAD

**Issue by AdamEssemaali** [Macuyiko/minecraft-python#49]
Searching on the internet I can’t find the whl and I don’t know how to do

**Comment by Macuyiko** [comment]
- Python 3.7 support is not happening soon. As Jython doesn't support Python 3. Using Py4J might be a way around this, but requires further investigation (first attempts didn't work well)
- Not sure why you would want to spin up Flask within a plugin which is running client-side? If you really do need a webserver there, perhaps taking a look at a Java alternative might be better

**Comment by AdamEssemaali** [comment]
Oh Ok thanks
