### ISSUE TITLE
Modifying Events before they happen doesn't work.

### ISSUE THREAD

**Issue by Iron-Chopper** [Macuyiko/minecraft-python#60]
Now I could just be dumb, but because I don't want to learn java, I'm simply wanting to make a plugin for a server that uses this project's python plugin to run it. In my code, I'm trying to make a simple event that whenever someone breaks a block it cancels the event and doesn't allow them to break the block. Another thing I want to do is make an event that changes the join message to nothing (so None or null). I get the result that the event is passed, and it even modifies the values because if I use the method of isCancelled() to see if it's canceled, and getJoinMessage() to see if the message is modified. The example code shows what I'm talking about.

```py
#import mcapi and events
from mcapi import *
from org.bukkit.events.player import PlayerJoinEvent
from org.bukkit.events.block import BlockBreakEvent
remove_event_listeners()

#Asynchronous function to be called for BlockBreakEvent
@asynchronous()
def blockBreak(event):
    event.setCancelled(True) #Cancel the event
    print(event) #Debug message to show its passed
    player = event.getPlayer() #Get the player who broke the block
    print(player) #Debug message to show player
    print(event.isCancelled()) #Boolean showing if it's been cancelled
    #This doesn't work.

@asynchronous
def playerJoin(event):
    event.setJoinMessage(None) #Set the join message to nothing
    player = event.getPlayer()
    print(event.getJoinMessage()) #ensure message is none or null
    #Doesn't Work correctly.
from org.bukkit.event import EventPriority #import priority to show its not that.
playerJoinListener = add_event_listener(
    PlayerJoinEvent,
    playerJoin,
    priority=EventPriority.MONITOR #bad practice but for points sake
)
blockBreakListener = add_event_listener(
    BlockBreakEvent,
    blockBreak,
    priority=EventPriority.MONITOR #bad practice but for points sake
)
```

**Comment by Macuyiko** [comment]
This works - place in a file e.g. `python-plugins/myplugin.py`

```
from mcapi import *
from org.bukkit.event.player import PlayerJoinEvent
from org.bukkit.event.block import BlockBreakEvent
# remove_event_listeners() # Not really needed as you might remove other event listeners

def blockBreak(event):
    event.setCancelled(True)

def playerJoin(event):
    event.setJoinMessage(None)

playerJoinListener = add_event_listener(
    PlayerJoinEvent,
    playerJoin
)

blockBreakListener = add_event_listener(
    BlockBreakEvent,
    blockBreak
)
```

E.g. you don't want asynchronous here, but keep this synchronized.

**Comment by Iron-Chopper** [comment]
Thank you very much for responding so quickly!
I guess I didn't fully understand what the asynchronous decorator did, but after looking at that part of mcapi.py I think I understand why that wouldn't work. I will probably test it on my own, but I would think that using the synchronous decorator would also work with it because that uses a spigot thread rather than a python thread, but, I don't want to take any more of your time, So thank you very much for your answer!
