### ISSUE TITLE
How to supply the password using ServerEditorWeb

### ISSUE THREAD

**Issue by pauleveritt** [Macuyiko/minecraft-python#7]
Hi, thanks for putting this up on GitHub. I'm trying to connect via a browser. It's giving an error message:

```
Login by sending 'login!<PASSWORD>'
```

I found what's sending that, in PyWebSocketServer.java. It appears that the base class from Java's WebSocketServer handles the extraction of a password, presumably from a ws://username:password@host:port URI scheme. I tried hardcoding that into minecraftclient.js but still got the error.

Sorry if this is a dumb question. I'm just starting into this code and I'm new to Jython/Java.

**Comment by pauleveritt** [comment]
I just needed to add a send('login!passwordhere'); line the click handler for #connectbutton

I'll close this.

**Comment by Macuyiko** [comment]
Correct. A `ws://username:password@host:port` makes more sense, in a way, but for now, the authentication scheme is kept deliberately bare bones. I never had much need to expand it and didn't want to commit to any heavyweight auth middleware at this stage.
